apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  chart:
    spec:
      version: 6.0.2
  values:
    image:
      tag: 0.1.2 # {"$imagepolicy": "dummy-apps:dummy-backend:tag"}
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: dummy-staging.quickanddirty.work
      rules:
        - host: dummy-staging.quickanddirty.work
          paths:
            - pathType: Prefix
              path: "/api"
      tls:
        - hosts:
            - dummy-staging.quickanddirty.work
          secretName: dummy-backend-tls
    autoscaling:
      enabled: true
