apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-frontend:dummy-frontend:name"}
      tag: 0.1.10 # {"$imagepolicy": "dummy-frontend:dummy-frontend:tag"}
    ingress:
      enabled: false
      ingressClassName: nginx
      rules:
        - host: dummy.review.cyberbrain.pw
          paths:
            - pathType: Prefix
              path: "/"
      tls:
        - hosts:
            - dummy.review.cyberbrain.pw
          secretName: dummy-frontend-tls
    autoscaling:
      enabled: false
