apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  values:
    image:
      tag: main-c68f7f4-1744214051070 # {"$imagepolicy": "dummy-apps-merged:dummy-backend:tag"}
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
        - host: dummy.lab-testing.home.arpa
          paths:
            - pathType: Prefix
              path: "/api"
      tls:
        - hosts:
            - dummy.lab-testing.home.arpa
          secretName: dummy-backend-tls
    autoscaling:
      enabled: false
