---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../lab-staging/dummy-apps-merged/dummy-backend
patches:
  - path: patch_helm-release.yaml
  - patch: |-
      $patch: delete
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImagePolicy
      metadata:
        name: dummy-backend
    target:
      kind: ImagePolicy
      name: dummy-backend
  - patch: |-
      $patch: delete
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      kind: ImageRepository
      metadata:
        name: dummy-backend
    target:
      kind: ImageRepository
      name: dummy-backend
