---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  install:
    timeout: 20m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
    crds: CreateReplace
    cleanupOnFail: true
  values:
    nameOverride: dummy-backend
    containerPort: 3000
    deploymentType: Deployment
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    livenessProbe:
      httpGet:
        path: /api
        port: default
      timeoutSeconds: 3
    readinessProbe:
      httpGet:
        path: /api
        port: default
      periodSeconds: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - dummy-backend
              topologyKey: "kubernetes.io/hostname"
    autoscaling:
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    image:
      repository: ghcr.io/disafronov/dummy-backend
