---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  interval: 10m
  url: https://dmitriysafronov.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  interval: 10m
  chart:
    spec:
      chart: default
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: dummy-backend
