apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 3.3.0
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:name"}
      tag: 0.0.52 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
        - host: dummy.staging.cyberbrain.pw
          paths:
            - pathType: Prefix
              path: "/"
      tls:
        - hosts:
            - dummy.staging.cyberbrain.pw
          secretName: dummy-frontend-tls
