apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 6.0.2
  values:
    image:
      tag: 0.1.24 # {"$imagepolicy": "dummy-apps:dummy-frontend:tag"}
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: dummy-staging.quickanddirty.work
      rules:
        - host: dummy-staging.quickanddirty.work
          paths:
            - pathType: Prefix
              path: "/"
      tls:
        - hosts:
            - dummy-staging.quickanddirty.work
          secretName: dummy-frontend-tls
    autoscaling:
      enabled: true
