apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  chart:
    spec:
      version: 6.0.2
  values:
    image:
      tag: 0.1.11 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
        - host: dummy.staging.cyberbrain.pw
          paths:
            - pathType: Prefix
              path: "/"
      tls:
        - hosts:
            - dummy.staging.cyberbrain.pw
          secretName: dummy-frontend-tls
    autoscaling:
      enabled: true
