apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: dummy-frontend
  namespace: dummy-frontend-review
spec:
  # This causes removal of templated objects in case they disappear from the rendered list of objects
  prune: true
  matrix:
    - name: pr
      object:
        ref:
          apiVersion: templates.kluctl.io/v1alpha1
          kind: ListGithubPullRequests
          name: dummy-frontend
        jsonPath: status.pullRequests
        expandLists: true
    - name: ingress
      object:
        ref:
          apiVersion: v1
          kind: ConfigMap
          name: ingress-dummy-frontend
        jsonPath: .data
  templates:
    - object:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
    - object:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: default
          namespace: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            name: default
            namespace: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
          # - apiGroup: rbac.authorization.k8s.io
          #   kind: User
          #   name: gotk:dummy-frontend:reconciler
    - object:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: "{{ matrix.pr.base.repo.name | slugify }}"
          namespace: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          path: ./overlays/lab-review/dummy-apps-merged
          sourceRef:
            kind: GitRepository
            name: dummy-apps
            namespace: tenants-dummy-apps
          interval: 5m0s
          timeout: 20m0s
          retryInterval: 2m0s
          wait: true
          prune: true
          force: true
          targetNamespace: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: dummy-frontend
                spec:
                  values:
                    image:
                      tag: "pr-{{ matrix.pr.number }}-{{ matrix.pr.merge_commit_sha[:7] }}"
                    ingress:
                      annotations:
                        external-dns.alpha.kubernetes.io/hostname: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                      rules:
                        - host: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                          paths:
                            - pathType: Prefix
                              path: "/"
                      tls:
                        - hosts:
                            - "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                          secretName: "tls-{{ matrix.pr.base.repo.name | slugify }}"
              target:
                kind: HelmRelease
                name: dummy-frontend
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2
                kind: HelmRelease
                metadata:
                  name: dummy-backend
                spec:
                  values:
                    ingress:
                      annotations:
                        external-dns.alpha.kubernetes.io/hostname: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                      rules:
                        - host: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                          paths:
                            - pathType: Prefix
                              path: "/api"
                      tls:
                        - hosts:
                            - "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}"
                          secretName: "tls-{{ matrix.pr.base.repo.name | slugify }}"
              target:
                kind: HelmRelease
                name: dummy-backend
    - object:
        apiVersion: templates.kluctl.io/v1alpha1
        kind: GithubComment
        metadata:
          name: "{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}"
          namespace: dummy-frontend-review
        spec:
          github:
            owner: "{{ matrix.pr.base.repo.owner.login }}"
            repo: "{{ matrix.pr.base.repo.name }}"
            pullRequestId: "{{ matrix.pr.number }}"
            tokenRef:
              secretName: github-token-dummy-frontend
              key: github-token
          comment:
            source:
              text: |
                Deployment will be ready in few seconds...

                ---

                **URL**: https://{{ matrix.pr.base.repo.name | slugify }}-{{ matrix.pr.number }}{{ matrix.ingress.suffix }}
