apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  values:
    ingress:
      ingressClassName: nginx
    autoscaling:
      enabled: false
