apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-backend
  namespace: dummy-backend
spec:
  values:
    image:
      tag: 0.0.17 # {"$imagepolicy": "dummy-backend:dummy-backend:tag"}
    ingress:
      enabled: false
      ingressClassName: nginx
      rules:
        - host: dummy.review.cyberbrain.pw
          paths:
            - pathType: Prefix
              path: "/api"
      tls:
        - hosts:
            - dummy.review.cyberbrain.pw
          secretName: dummy-backend-tls
    autoscaling:
      enabled: false
