apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dummy-frontend
  namespace: dummy-frontend
spec:
  values:
    image:
      repository: ghcr.io/dmitriysafronov/dummy-frontend # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:name"}
      tag: main-c0e5cac-1743433119907 # {"$imagepolicy": "dummy-apps-merged:dummy-frontend:tag"}
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
        - host: dummy.lab-testing.home.arpa
          paths:
            - pathType: Prefix
              path: "/"
      tls:
        - hosts:
            - dummy.lab-testing.home.arpa
          secretName: dummy-frontend-tls
    autoscaling:
      enabled: false
