---
name: Yamllint on pull request to main
"on":
  pull_request:
    branches: [main]
jobs:
  yamllint:
    name: Yamllint on pull request to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
      - name: Run yamllint
        uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
